version: "3.4"
services: 
    mariadb:
        image: mariadb:10.2
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
        restart: on-failure
        volumes:
            - /path/to/mariadb-persistence:/bitnami/mariadb

    api:
        image: node:latest
        container_name: api
        restart: always
        env_file:
            - .env
        depends_on:
            - mariadb
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        command: npm run dev
        links: 
            - mariadb