version: "3.4"
services: 
    mariadb:
        image: mariadb:10.2
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
        restart: on-failure
        volumes:
            - /path/to/mariadb-persistence:/bitnami/mariadb